# Changes here will be overwritten by Copier
_commit: 6eafa40
_src_path: gh:jlevy/simple-modern-pnpm
author_email: joshua@cal.berkeley.edu
author_name: Joshua Levy
github_org: jlevy
package_description: Knowledge flows for agents
package_name: signposts
repo_name: signposts
workspace_name: signposts
